const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true })
var testResults = 'Passed'
const vars = require('../../../TestVariables')


nightmare
  .viewport(1200, 1000)
  .goto(vars.mainUrl + '/login')
  .wait(2000)
  // .screenshot('../../../Testing Screenshots/forgot_password/correct-website.png')
  .click('.forgot-link')
  .wait(1000)
  .click('#ed_293610560')
  .wait(500)
  .type('#ed_293610560', vars.notValidEmail)
  .wait(500)
  .click('#ed_293610561')
  .wait(2000)
  // .screenshot('../../../Testing Screenshots/forgot_password/invalid_email.png')
  .click('#ed_293610560')
  .wait(500)
  .type('#ed_293610560', 'm')
  .wait(500)
  // .screenshot('../../../Testing Screenshots/forgot_password/correct_email.png')
  .click('#ed_293610562')
  .wait(3000)
  // .screenshot('../../../Testing Screenshots/forgot_password/forgot_password_sent.png')

  .end()
    .then(function (result) {
      console.log('    ')
      console.log('    ')
      console.log('  FORGOT PASSWORD - TEST RESULTS: ')
      console.log('    ')
      console.log('    + Directed To Correct Website:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Click Forgot Password Link:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Add Employee Email', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Clicked Signin Button:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Not Valid Email Verification:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Valid Email Submitted:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    ')
      console.log('  TEST COMPLETED ')
      console.log('    ')
      console.log('    ')
    })
    .catch(function (error) {
      console.error('Error:', error);
    })
