
const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true })
var testResults = 'Passed'
const url = 'http://localhost:3000'


nightmare
  .viewport(1200, 1000)
  .goto(url + '/login')
  .wait(500)
  .screenshot('../../../Testing Screenshots/admin_permissions/correct-website.png')
  .click('#ed_293610547')
  .wait(1000)
  .insert('#ed_293610547', 'eddyhr.test1@gmail.com')
  .wait(500)
  .click('#ed_293610546')
  .wait(1000)
  .type('#ed_293610546', 'Eddyhr!123')
  .wait(500)
  .screenshot('../../../Testing Screenshots/admin_permissions/correct-auth.png')
  .click('.ed-btn-sign-in')
  .wait(2000)
  .click('#ed_293610591')
  .screenshot('../../../Testing Screenshots/admin_permissions/admin-can-filter.png')
  .wait(500)
  .screenshot('../../../Testing Screenshots/admin_permissions/edit-modal-opened.png')
  .wait(500)
  .goto(url + '/employee/personal/1510865716190')
  .wait('#ed_293610579')
  .wait(500)
  .screenshot('../../../Testing Screenshots/admin_permissions/employee-profile.png')
  .click('#ed_293610579')
  .wait(500)
  .screenshot('../../../Testing Screenshots/admin_permissions/edit-personal-modal-opened.png')
  .wait(500)
  .click('.close-modal')
  .wait(500)
  .click('#ed_293610592')
  .wait(500)
  .screenshot('../../../Testing Screenshots/admin_permissions/edit-contact-modal-opened.png')
  .wait(500)
  .click('.close-modal')
  .wait(500)
  .click('#ed_293610593')
  .wait(500)
  .screenshot('../../../Testing Screenshots/admin_permissions/edit-emergency-contact-modal-opened.png')
  .wait(500)
  .click('.close-modal')
  .wait(500)
  .click('#ed_293610594')
  .wait(500)
  .screenshot('../../../Testing Screenshots/admin_permissions/edit-social-opened.png')
  .wait(500)
  .click('.close-modal')
  .wait(500)
  .click('#ed_f_name293610599')
  .click('#ed_pref_name293610600')
  .click('#ed_b_day293610601')
  .click('#ed_shirt293610602')
  .click('#ed_mid_initial293610603')
  .click('#ed_gender293610604')
  .click('#ed_marital_stat293610605')
  .click('#ed_l_name293610606')
  .click('#ed_gender_iden293610607')
  .click('#ed_ssn293610608')
  .wait(500)
  .click('#ed_293610596')
  .wait(500)
  .click('#ed_293610609')
  .wait(500)
  .screenshot('../../../Testing Screenshots/admin_permissions/edit-job-opened.png')
  .click('.close-modal')
  .wait(500)
  .click('#ed_293610610')
  .wait(500)
  .screenshot('../../../Testing Screenshots/admin_permissions/edit-bonus-opened.png')
  .click('.close-modal')
  .wait(500)
  .click('#ed_293610619')
  .wait(1000)
  .insert('#ed_293610621', 'Hitting Goals - ' + Date.now())
  .wait(500)
  .type('#ed_293610622', '\u000d')
  .wait(2000)
  .insert('#ed_293610623', '900')
  .wait(1000)
  .click('#ed_293610623')
  .wait(500)
  .type('#ed_293610624', 'Great Job Yo!!')
  .wait(1000)
  .screenshot('../../../Testing Screenshots/admin_permissions/bonus-added.png')
  .click('#ed_293610620')
  .wait(4000)
  .click('#ed_293610611')
  .wait(500)
  .screenshot('../../../Testing Screenshots/admin_permissions/edit-compensation-opened.png')
  .click('.close-modal')
  .wait(500)
  .click('#ed_293610612')
  .wait(500)
  .screenshot('../../../Testing Screenshots/admin_permissions/edit-assets-opened.png')
  .click('.close-modal')
  .wait(500)
  .click('#ed_293610613')
  .wait(1000)
  .screenshot('../../../Testing Screenshots/admin_permissions/edit-direct-reports-opened.png')
  .click('.close-modal')
  .wait(500)
  .click('#ed_293610597')
  .wait(500)
  .insert('#ed_293610614', 'New Note - ' + Date.now())
  .wait(500)
  .insert('#ed_293610615', 'The current date and time is ' + Date())
  .wait(500)
  .click('#ed_293610625')
  .wait(2000)
  .click('#ed_293610616')
  .wait(1000)
  .click('#ed_293610617')
  .wait(1000)
  .click('#ed_293610618')
  .wait(3000)
  .click('#ed_293610598')
  .wait(1000)
  .end()
    .then(function (result) {
      console.log('    ')
      console.log('    ')
      console.log('  ADMIN EDIT SELF - TEST RESULTS: ')
      console.log('    ')
      console.log('    + Directed To Correct Website:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Log In To Admin Account:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can Invite Employees:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can Filter By Status:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can View All Personal Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can EDIT All Personal Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can View All Contact Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can EDIT All Contact Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can View All Emergency Contact Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can EDIT All Emergency Contact Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can View All Social Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can EDIT All Job Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can VIEW All Job Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can EDIT All Bonus Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can VIEW All Bonus Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Create Bonus Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can VIEW All EEO FSLA Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can EDIT All Compensation Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can VIEW All Compensation Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can EDIT All Assets Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can VIEW All Assets Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can EDIT All Direct Reports Card:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Can VIEW All Direct Reports Card:', testResults)
      console.log('    --------------------------------------------------')
      

      console.log('    ')
      console.log('  TEST COMPLETED ')
      console.log('    ')
      console.log('    ')
    })
    .catch(function (error) {
      console.error('Error:', error);
    })
