const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true })
var testResults = 'Passed'
const url = 'http://localhost:3000'

nightmare
  .viewport(1200, 1000)
  .goto(url + '/login')
  .wait(2000)
  .screenshot('../../../Testing Screenshots/company_enrollment/correct-website.png')
  .wait('.sign-up')
  .click('.sign-up')
  .wait('#ed_293610563')
  .wait(300)
  .screenshot('../../../Testing Screenshots/company_enrollment/enrollment_options.png')
  .click('#ed_293610563')
  .wait('#ed_293610564')
  .wait(500)
  .screenshot('../../../Testing Screenshots/company_enrollment/selected_company_enrollment.png')
  .insert('#ed_293610564', 'Daniel')
  .wait('#ed_293610565')
  .insert('#ed_293610565', 'Dumphy')
  .wait(200)
  .insert('#ed_293610566', 'eddyhr.test5@gmail.com')
  .wait(200)
  .type('#ed_293610567', 'Eddyhr!123')
  .wait(200)
  .type('#ed_293610568', 'Eddyhr!123')
  .wait(200)
  .screenshot('../../../Testing Screenshots/company_enrollment/personal_info_added.png')
  .click('#ed_293610569')
  .wait(500)
  .click('#ed_293610570')
  .wait('#ed_293610571')
  .insert('#ed_293610571', 'Daniels Construction Company')
  .wait(500)
  .click('#ed_293610572')
  .wait(1000)
  .select('#ed_293610573', 'Consumer Goods')
  .wait(200)
  .select('#ed_293610574', '11-50 people')
  .wait(200)
  .select('#ed_293610575', 'HR Manager')
  .wait(200)
  .select('#ed_293610576', 'Yes, HR software is new to us!')
  .wait(500)
  .screenshot('../../../Testing Screenshots/company_enrollment/company_info_added.png')
  .click('#ed_293610577')
  .wait(3000)
  .screenshot('../../../Testing Screenshots/company_enrollment/company_added.png')
  .end()
    .then(function (result) {
      console.log('    ')
      console.log('    ')
      console.log('  COMPANY ENROLLMENT - TEST RESULTS: ')
      console.log('    ')
      console.log('    + Directed To Correct Website:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Click Sign Up Now:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Click Company Admin:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Add Admin First Name:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Add Admin Last Name:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Add Admin Email:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Add Admin Password:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Confirm Admin Password:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Add Company Name:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Add Other Company Info:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Submit Company / Verify Email:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    ')
      console.log('  TEST COMPLETED ')
      console.log('    ')
      console.log('    ')
    })
    .catch(function (error) {
      console.error('Error:', error);
    })
