const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true })
var testResults = 'Passed'
const url = 'http://localhost:3000'

nightmare
  .viewport(1200, 1000)
  .goto(url + '/login')
  .wait(2000)
  .screenshot('../../../Testing Screenshots/create_employee_account_attempt/correct-website.png')
  .wait('.sign-up')
  .click('.sign-up')
  .wait('#ed_293610563')
  .wait(1000)
  .screenshot('../../../Testing Screenshots/create_employee_account_attempt/employee_enrollment.png')
  .click('.employee-container')
  .wait(1000)
  .screenshot('../../../Testing Screenshots/create_employee_account_attempt/not_able_to_enroll.png')
  .click('#ed_293610578')
  .wait(1000)
  .click('.employee-container')
  .wait(500)
  .click('#ed_293610578')
  .wait(2000)
  .end()
    .then(function (result) {
      console.log('    ')
      console.log('    ')
      console.log('  COMPANY ENROLLMENT - TEST RESULTS: ')
      console.log('    ')
      console.log('    + Directed To Correct Website:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Click Sign Up Now:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Click Company Employee:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Click Back Button:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Click Company Employee:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Click Back Button:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    ')
      console.log('  TEST COMPLETED ')
      console.log('    ')
      console.log('    ')
    })
    .catch(function (error) {
      console.error('Error:', error);
    })
