const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true })
var testResults = 'Passed'


nightmare
  .goto('http://localhost:3000/login')
  .wait(2000)
  .click('.forgot-link')
  .wait(1000)
  .click('#ed_293610560')
  .wait(500)
  .type('#ed_293610560', 'eddyhr.test1@gmail.co')
  .wait(500)
  .click('#ed_293610561')
  .wait(2000)
  .click('#ed_293610560')
  .wait(500)
  .type('#ed_293610560','m')
  .wait(500)
  .click('#ed_293610562')
  .wait(3000)

  .end()
    .then(function (result) {
      console.log('    ')
      console.log('    ')
      console.log('  TEST RESULTS: ')
      console.log('    ')
      console.log('    + Directed To Correct Website:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Click Forgot Password Link:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Add Employee Email', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Clicked Signin Button:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Not Valid Email Verification:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    + Valid Email Submitted:', testResults)
      console.log('    --------------------------------------------------')
      console.log('    ')
      console.log('  TEST COMPLETED ')
      console.log('    ')
      console.log('    ')
    })
    .catch(function (error) {
      console.error('Error:', error);
    })
